/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package flow_assignment_01;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armandi
 */
public class PeopleProfiles extends javax.swing.JFrame {

   DefaultTableModel model;
   
    public PeopleProfiles() {
        initComponents();
        model = (DefaultTableModel)viewPersonsTable.getModel();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personProfiles = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        administrator = new javax.swing.JLabel();
        analyst = new javax.swing.JLabel();
        finisher = new javax.swing.JLabel();
        creative = new javax.swing.JLabel();
        comments = new javax.swing.JLabel();
        viewAddButton = new javax.swing.JButton();
        viewEditButton = new javax.swing.JButton();
        viewDeleteButton = new javax.swing.JButton();
        viewSaveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        nameTF = new javax.swing.JTextField();
        administratorTF = new javax.swing.JTextField();
        analystTF = new javax.swing.JTextField();
        creativeTF = new javax.swing.JTextField();
        finisherTF = new javax.swing.JTextField();
        commentsTF = new javax.swing.JTextField();
        viewTable = new javax.swing.JScrollPane();
        viewPersonsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        personProfiles.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        personProfiles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personProfiles.setText("Person profiles");

        name.setText("Name:");

        administrator.setText("Administrator:");

        analyst.setText("Analyst:");

        finisher.setText("Finisher:");

        creative.setText("Creative:");

        comments.setText("Comments");

        viewAddButton.setText("Add");
        viewAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAddButtonActionPerformed(evt);
            }
        });

        viewEditButton.setText("Edit");
        viewEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEditButtonActionPerformed(evt);
            }
        });

        viewDeleteButton.setText("Delete");
        viewDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDeleteButtonActionPerformed(evt);
            }
        });

        viewSaveButton.setText("Save");

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        nameTF.setText("Name");

        administratorTF.setText("1-30");

        analystTF.setText("1-30");
        analystTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analystTFActionPerformed(evt);
            }
        });

        creativeTF.setText("1-30");
        creativeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creativeTFActionPerformed(evt);
            }
        });

        finisherTF.setText("1-30");

        commentsTF.setText("Write your comment here...");

        viewPersonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ADMINISTRATOR", "ANALYST", "CREATIVE", "FINISHER", "COMMENTS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        viewPersonsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPersonsTableMouseClicked(evt);
            }
        });
        viewTable.setViewportView(viewPersonsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(administrator)
                            .addComponent(analyst, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(analystTF, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(administratorTF))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(creative)
                                    .addComponent(finisher))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(creativeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(finisherTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(comments)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(commentsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewAddButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewEditButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewDeleteButton))))
                    .addComponent(viewTable, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personProfiles)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(administratorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(administrator)
                            .addComponent(creative)
                            .addComponent(creativeTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(analystTF)
                            .addComponent(finisher)
                            .addComponent(finisherTF)
                            .addComponent(analyst))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comments)
                            .addComponent(commentsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addComponent(viewTable, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEditButtonActionPerformed
    model.setValueAt(nameTF.getText(), viewPersonsTable.getSelectedRow(), 0);
    model.setValueAt(administratorTF.getText(), viewPersonsTable.getSelectedRow(), 1);
    model.setValueAt(analystTF.getText(), viewPersonsTable.getSelectedRow(), 2);
    model.setValueAt(creativeTF.getText(), viewPersonsTable.getSelectedRow(), 3);
    model.setValueAt(finisherTF.getText(), viewPersonsTable.getSelectedRow(), 4);
    model.setValueAt(commentsTF.getText(), viewPersonsTable.getSelectedRow(), 5);
    
    }//GEN-LAST:event_viewEditButtonActionPerformed

    private void viewAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAddButtonActionPerformed
        model.insertRow(model.getRowCount(), new Object[]{nameTF.getText(), administratorTF.getText(), analystTF.getText(), creativeTF.getText(), finisherTF.getText(), commentsTF.getText()});
    }//GEN-LAST:event_viewAddButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadButtonActionPerformed

    private void analystTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analystTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analystTFActionPerformed

    private void creativeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creativeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creativeTFActionPerformed

    private void viewPersonsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPersonsTableMouseClicked
   nameTF.setText(String.valueOf(model.getValueAt(viewPersonsTable.getSelectedRow(), 0)));
   administratorTF.setText(String.valueOf(model.getValueAt(viewPersonsTable.getSelectedRow(), 1)));
    analystTF.setText(String.valueOf(model.getValueAt(viewPersonsTable.getSelectedRow(), 2)));
    creativeTF.setText(String.valueOf(model.getValueAt(viewPersonsTable.getSelectedRow(), 3)));
    finisherTF.setText(String.valueOf(model.getValueAt(viewPersonsTable.getSelectedRow(), 4)));
    commentsTF.setText(String.valueOf(model.getValueAt(viewPersonsTable.getSelectedRow(), 5)));
    }//GEN-LAST:event_viewPersonsTableMouseClicked

    private void viewDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDeleteButtonActionPerformed
    model.removeRow(viewPersonsTable.getSelectedRow());
    }//GEN-LAST:event_viewDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeopleProfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeopleProfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeopleProfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeopleProfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeopleProfiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel administrator;
    private javax.swing.JTextField administratorTF;
    private javax.swing.JLabel analyst;
    private javax.swing.JTextField analystTF;
    private javax.swing.JLabel comments;
    private javax.swing.JTextField commentsTF;
    private javax.swing.JLabel creative;
    private javax.swing.JTextField creativeTF;
    private javax.swing.JLabel finisher;
    private javax.swing.JTextField finisherTF;
    private javax.swing.JButton loadButton;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel personProfiles;
    private javax.swing.JButton viewAddButton;
    private javax.swing.JButton viewDeleteButton;
    private javax.swing.JButton viewEditButton;
    private javax.swing.JTable viewPersonsTable;
    private javax.swing.JButton viewSaveButton;
    private javax.swing.JScrollPane viewTable;
    // End of variables declaration//GEN-END:variables
}
